export const GET_THERPIST_PENDING='GET_THERPIST_PENDING'
export const GET_THERPIST_SUCCESS='GET_THERPIST_SUCCESS'
export const GET_THERPIST_ERROR='GET_THERPIST_ERROR'
export const GET_PROFILE_PENDING='GET_PROFILE_PENDING'
export const GET_PROFILE_SUCCESS='GET_PROFILE_SUCCESS'
export const GET_PROFILE_ERROR='GET_PROFILE_ERROR'


